# Generated by Django 3.0.8 on 2020-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frais_deLivraison',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantité',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='quantité'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=90, null=True, verbose_name='description'),
        ),
    ]
